### ISSUE TITLE
students.csv is missing

### ISSUE THREAD

**Issue by jkhlr** [HPI-Information-Systems/spark-tutorial#1]
The resource `data/students.csv` is loaded in [`SimpleSpark.scala`](https://github.com/HPI-Information-Systems/spark-tutorial/blob/master/src/main/scala/de/hpi/spark_tutorial/SimpleSpark.scala#L415), but is not present in the repository.

**Comment by thorsten-papenbrock** [comment]
Many thanks for pointing that out! 

The commit eb2a5aa13ad5b99cf965e3159a2cdf5be8e5fed1 added the missing `data/students.csv` file.
